LEVEL_SCROLL_NONE   = $00
LEVEL_SCROLL_LEFT	= $01
LEVEL_SCROLL_RIGHT	= $02

HERO_TITLE_SCREEN_Y_OFFSET  = $78
HERO_GAME_SCREEN_Y_OFFSET   = $80

HERO_X_OFFSET_LEFT  = $50
HERO_X_OFFSET_RIGHT = $80

;******************************************************************************
;** Events related ************************************************************
;******************************************************************************

;*** Game Screen related ***

EVENT_GAME_SCREEN_COPY_OAM                  = $00
EVENT_GAME_SCREEN_TRANSFER_HERO_SPRITE_DATA = $01
EVENT_GAME_SCREEN_LEVEL                     = $02
EVENT_GAME_SCREEN_SCORE                     = $03
