.import initFont
.import setFontPalette
.import enableSkipSpaces
.import disableSkipSpaces
.import enableSkipLeadingZero
.import disableSkipLeadingZero
.import setFontCursorPosition
.import setFontCursorPositionNewLine
.import writeFontString
.import writeFontNumber
.import clearFontZone

.import fontTiles
.import letterGreyPal
.import letterRedPal

.import titleScreenWhitePal
.import titleScreenYellowPal
.import titleScreenWhiteRedPal

.import gameMessagePal
.import fontWhiteRedBlackPal
.import fontRedBlackBlackPal
.import fontCyanBlackBlackPal

.import letterIntroString
.import titleScreenSelectString
.import titleScreenCopyrightString
.import readyString
.import onePlayerFirstFloorString
.import gamePausedString