#CC65_HOME=/home/lint/Snes/cc65
#CC65_BIN=$(CC65_HOME)/bin

#SFCLIB_PATH=/home/lint/Dropbox/Snes/projects/Snes_Tools/sfclgit statusib/bin
#CFG_PATH=/home/lint/Dropbox/Snes/projects/Snes_Tools/sfclib/cfg

CC65_HOME=../../Tools/cc65-master
CC65_BIN=$(CC65_HOME)/bin

SFC_LIB_HOME=../../Tools/cc65-sfclib
SFC_LIB_PATH=$(SFC_LIB_HOME)/bin
SFC_CFG_PATH=$(SFC_LIB_HOME)/cfg
SFC_INC_PATH=$(SFC_LIB_HOME)/include
